package org.univalle.parser;

import java.io.*;

public class Sparql2Flink {
    public static void main(String[] args) throws Exception {
        // The name of the file to open.
        System.out.println((new File("./src/main/java/org/univalle/parser/Query1.txt").getAbsolutePath()));
        System.out.println((new File("./src/main/java/org/univalle/flink/Query.java").getAbsolutePath()));
        String fileName = "./src/main/java/org/univalle/parser/Query1.txt";
        String classFileName = "./src/main/java/org/univalle/flink/Query.java";
        // This will reference one line at a time
        String line = null;

        try {
            //This is just an example. The source code will be generated by the tool from the SPARQL query
            FileReader fileReader = new FileReader(fileName);

            // Always wrap FileReader in BufferedReader.
            BufferedReader bufferedReader =
                    new BufferedReader(fileReader);


            // Assume default encoding.
            FileWriter fileWriter =
                    new FileWriter(classFileName);

            // Always wrap FileWriter in BufferedWriter.
            BufferedWriter bufferedWriter =
                    new BufferedWriter(fileWriter);

            // Always close files.
            while((line = bufferedReader.readLine()) != null) {
                //System.out.println(line);
                bufferedWriter.write(line);
                bufferedWriter.newLine();
            }

            // Always close files.
            bufferedReader.close();
            bufferedWriter.close();

        }
        catch(FileNotFoundException ex) {
            System.out.println(
                    "Unable to open file '" +
                            fileName + "'");
        }
        catch(IOException ex) {
            System.out.println(
                    "Error reading file '"
                            + fileName + "'");
            // Or we could just do this:
            // ex.printStackTrace();
        }
    }
}
